name: Sam Wolfand
favicon: null
layout_spectrum: 0.24056164268404245
typography_spectrum: 0.2843723548576236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12734681158326566
  lightness: 0.920980203198269
  saturation: 0.20943323988467455
  rhythmicContrast: 0.2200197943020612
purpose: []
